### ISSUE TITLE
Relationships support

### ISSUE THREAD

**Issue by neomerx** [neomerx/limoncello-ember#1]
Currently this application can add/edit models with attributes only (without relationships). Such models as `Comment` and `Post` have relationships with other models and this application can't create/edit them. 

Support needed for
- loading available option values
- showing the options in select control (drop-down list)
- proper model update and save

Server side is [Limoncello Shot](https://github.com/neomerx/limoncello-shot) and already installed on server with IP `46.101.189.195` on port 80.

The ember app should work with it out of the box.

**Comment by neomerx** [comment]
@lindyhopchris I would appreciate if you could help me with this issue.

**Comment by lindyhopchris** [comment]
@neomerx will take a look at this tonight when I'm home as I can't look at this while at work.

**Comment by neomerx** [comment]
@lindyhopchris I've added authentication support and some IU styling and this issue with relationships is the main one. I've tried to use `select` and the main problem I had was with data loading for relationships. Ember has method for loading `model` but how can I load a few more collections that this model use? I haven't found any good examples of that. All the examples I've found just set a hardcoded list of values.

The only idea I have is create a `Component` for authors selection. It should have its own data load for model and if properties for getting/setting current `Author` is added it might work. Do you think it's a good approach or there are better one?

**Comment by lindyhopchris** [comment]
Hi @neomerx 

Sorry for not replying earlier this week - having a manic week in work and out of work, so haven't had time to look at this yet.

The way I always do relationships that need to be set in `<select>` elements is to resolve the models that need to appear in the route's `model` hook.

E.g. if you have a route for editing a `foo` model, and that has a belongs to `bar` model. If I want to offer a `<select>` element for selecting the `bar` model, then my route's `model` hook will look like this:

``` javascript
model: function () {
    return Ember.RSVP.hash({
         foo: this.store.createRecord('foo'),
         bars: this.store.findAll('bar')
    });
}
```

Then in the template, I'll be using `this.bars` as the values to select from in the `<select>` element. As they are resolved models, then you don't need to worry about handling promises in the components. (This should all get easier when they add async-components, which I believe are going to be introduced in the 2.x series.)

The other thing to help is to use an add-on for the select element. This one is an option but there are others:
https://github.com/thefrontside/emberx-select

**Comment by neomerx** [comment]
@lindyhopchris I've can set relationship while creating new `Comment` objects but can't edit it for existing ones. I do need your help with it. Could you please have a look?

I've created external server for it so you'll need just clone the project and `ember s` it.

Thanks

**Comment by lindyhopchris** [comment]
@neomerx 

what do i use to sign in?

**Comment by neomerx** [comment]
user@example.com password

**Comment by lindyhopchris** [comment]
@neomerx 

just pushed a commit that allows setting the `post` on an existing `comment`. Hope it's what you're after. The thing that's a potential gotcha is to get the select displaying the current selected post on render, you need to have resolved the current selected post in the model hook on the route. That's because if in the template you just do `{{#x-select value=model.comment.post}}`, that returns a promise object (as it's an async relationship), which is not going to be the same as any of the post values on the `{{#x-option}}` components.

The other thing is that now that I've changed the model on the edit route, when using a `link-to` helper you'll need to pass `comment.id` as the value rather than just `comment`, as the route's model is no longer just a comment model.

**Comment by neomerx** [comment]
@lindyhopchris Thanks a lot. I've been playing with the code for a while and learnt something about Ember. To my surprise some things work and other very similar don't :smile:

**Comment by neomerx** [comment]
@lindyhopchris We are live :fire: I would like to especially thank you for your invaluable help and advice. You are a :star2:

**Comment by lindyhopchris** [comment]
@neomerx no problem!
