### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by neomerx** [neomerx/limoncello-ember#2]
The app should work with authentication
- intercept not authenticated API calls
- show login form and get JWT (`/login/basic` URL) from server with Basic Auth (login `user@example.com`, password `password`)
- use the JWT with all further API ('Bearer ' + JWT in `Authorization` HTTP header) calls to server until JWT is expired

Server side is [Limoncello Shot](https://github.com/neomerx/limoncello-shot) and already installed on server with IP `46.101.189.195` on port **8080**.

The ember app needs to be updated [in configuration](https://github.com/neomerx/limoncello-ember/blob/develop/config/environment.js#L3) in order to work with JWT protected server.

**Comment by neomerx** [comment]
@lindyhopchris It would be really nice if you could help me with this one as well however if you can do only 1 then #1  is more important.

**Comment by lindyhopchris** [comment]
@neomerx 

Have you seen Ember Simple Auth? https://github.com/simplabs/ember-simple-auth

That's what a lot of people use for Ember authentication and I believe it should work for this scenario.

**Comment by neomerx** [comment]
@lindyhopchris Thanks for the hint. I've got some progress on this issue with it. I have login form, protected route and I can get JWT. Now I have to configure Authenticator and Authorizer. I think I need custom Authenticator and built-in Bearer Authorizer.

Learning Ember is fun :smile: I like it however I wish it would be easier

**Comment by neomerx** [comment]
@lindyhopchris I think I have preliminary version pushed to `feature/issue2` branch. I'd like to check it against ember-simple-auth source code comments more carefully.

Also I've got a couple OMFG moments to share :smiley: 

## 1
The documentation says I have to add
```js
//config/environment.js
ENV['simple-auth'] = {
  authorizer: 'simple-auth-authorizer:oauth2-bearer'
}
```
OK I did that however I've got Error: Assertion Failed: The configured authorizer "simple-auth-authorizer:oauth2-bearer" could not be found in the container!

I tried to solve the problem with injection for a few hours. Solution? I had to just restart the ember! OMFG

## 2
I did custom authorizer which seemed to work and saved JWT to session however requests to server were without `Authorization` header. I spent couple of hours until I found [this line](https://github.com/simplabs/ember-simple-auth/blob/master/packages/ember-simple-auth-oauth2/lib/simple-auth-oauth2/authorizers/oauth2.js#L31) that caused the problem (Ember is my first JS experience). Thanks god I realized I had to use special naming for token in `authenticate`

```js
  authenticate(credentials) {

   ...
    return new Ember.RSVP.Promise(function(resolve, reject) {
      Ember.$.ajax({
        url: LOGIN_BASIC_URL,
        headers: {Authorization: basicHeaderValue}
      }).then((jwt) => {
        Ember.run(() => {
          resolve({ access_token: jwt }); // !!!!!!!!!!!!!!!!!!! MUST be 'access_token'
        });
      }, (xhr/*, status, error*/) => {
        let response = JSON.parse(xhr.responseText);
        Ember.run(() => {
          reject(response.error);
        });
      });
    });
  },
```
